Want to merge feature branch to master branch
Kingobaino1/New-York-Times-Page-Clone pull request #1
Opened 2020-08-25 15:52 UTC by Kingobaino1

**In this project**
- added navbar
- added header
- added body 
- added contents of body
- added a side-bar
- added footer

2020-08-25 17:03 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️


#### Overall the project looks really nice and I can see that you guys are working hard on it, and don't worry, you're almost done, there are just some required changes that you guys have to implement to proceed:


_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.

## [REQUIRED CHANGES]
#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [x] Please remove that images folder who is inside the CSS folder.
- [x] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/91204461-84977980-e6da-11ea-8304-8d494ae414b2.png)

#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [x] Your page has some overlapping, please take care of it 💪
![image](https://user-images.githubusercontent.com/56762529/91204482-8cefb480-e6da-11ea-8b2d-44c2449ecef3.png)
- [x] It uses [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the righmost side. , kindly remove that `<div>`. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
![image](https://user-images.githubusercontent.com/56762529/91204849-05567580-e6db-11ea-8d93-65f7012ba999.png)



## [OPTIONAL CHANGES]
- [ ] Add the title of the original page;
- [ ] Add a favicon to make it more similar to the original page;

#### Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question about this review? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-08-25 17:03 UTC, kevincappuccino commented on CSS/style.css
> +#marg_bot {
- [ ] [OPTIONAL] Use class instead 🔧

2020-08-25 23:13 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

## Hi team, good job on making the previously required changes!
Your page meets most of the requirements  👏 
You just have to implement some minor changes in order to move on
 
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [x] Your page still has some overlapping, please take care of it 👀
![image](https://user-images.githubusercontent.com/56762529/91236492-6ba8bb80-e70e-11ea-9551-bb29b052ae4d.png)
- The original one: 
![image](https://user-images.githubusercontent.com/56762529/91236632-d823ba80-e70e-11ea-9663-5be01fba6186.png)
Tip: Check paddings, margings, position and other spacing options to solve that issue 👷‍♂️

## [OPTIONAL CHANGES]
- [x] Add a favicon to make it more similar to the original page;
- [ ] Fix the font sizing to make it more similar to the original page;

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

  
<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-26 16:35 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

## Hi team, good job on making the previously required changes, however looks like you guys fixed the overlapping in the wrong way (using font-size), please take care of it! 💪
You just have to implement some minor changes in order to move on
 
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [x] Now your page has a font too small 😅 (Remember guys, is a clone, so make it look like a clone);
![image](https://user-images.githubusercontent.com/56762529/91330676-2634ce80-e7a0-11ea-9f4c-fd7892581308.png)

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

  
<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-26 19:18 UTC, Kingobaino1 commented
We have used vw for the font which are below these two pictures but now we corrected this. But now it has a different structure comparing to the previous one and it is responsive now.

2020-08-26 19:27 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

## Hello @Kingobaino1 and @hamayun-cpu  :wave: 

## Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

## You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-26 19:30 UTC, merged